server {
    listen       8081;# 配置端口
    server_name  localhost; # 修改为docker服务宿主机的ip或直接写localhost
 
    location / {
        root   /usr/share/nginx/html; # 网站的根目录在html文件夹
        index  index.html index.htm; # 定义访问的时候第一个被访问的页面，左边的优先级最高
        try_files $uri $uri/ /index.html =404;
    }
 
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}
